// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWFQMPUqBHuqS39TFjSsxlK25d8hnXFME',
    appId: '1:839427436959:web:1b1a7863df10aab48d4daa',
    messagingSenderId: '839427436959',
    projectId: 'flutter-food-delivery-d535b',
    authDomain: 'flutter-food-delivery-d535b.firebaseapp.com',
    storageBucket: 'flutter-food-delivery-d535b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tbBL2UyBk4mBZo0XQF-eY53jOowcWZA',
    appId: '1:839427436959:android:fdb8602248563d3c8d4daa',
    messagingSenderId: '839427436959',
    projectId: 'flutter-food-delivery-d535b',
    storageBucket: 'flutter-food-delivery-d535b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_miHYlMM0zuYwxKKztHqQSw2lTLiAK3w',
    appId: '1:839427436959:ios:001342f9dcd980398d4daa',
    messagingSenderId: '839427436959',
    projectId: 'flutter-food-delivery-d535b',
    storageBucket: 'flutter-food-delivery-d535b.appspot.com',
    iosBundleId: 'com.example.flutterFoodDeliveryApp',
  );
}
